### ISSUE TITLE
Highlighted braces in comments

### ISSUE THREAD

**Issue by benswinburne** [nextmn/vim-yaml-jinja#8]
It seems that braces in lines which are commented out follow the jinja colour scheme rather than that of the comments

<img width="423" alt="image" src="https://github.com/user-attachments/assets/9dd2c05b-f8c5-4cc9-8e1b-3f626026b97d">

Also in this example the # for the comment is highlighted

<img width="552" alt="image" src="https://github.com/user-attachments/assets/67ab8cc9-e354-4a68-bf23-13170522f935">

Is this a bug in this plugin or a misconfiguration on my side?

Thanks

**Comment by louisroyer** [comment]
Hi,

when using yaml comment (`#` on start of line), jinja code will still be evaluated on this line because default jinja comment syntax (that will avoid your jinja code to be evaluated) is different : `{# example of comment block #}`.

In the 2nd example jinja will error because the `#` on line 7 (which is colored) is an unexpected character in the `if` statement.

Jinja coloration inside yaml comment is an intended behavior, not a bug, and the plugin seems correctly configured on your side.

**Comment by benswinburne** [comment]
Thanks for getting back to me.

Understood about the unexpected character. It's valid and runs, but appears I should actually be placing parentheses around the multi line statement to be fully correct - when using parens around this, the # is still highlighted. I can live with this though.

Is there a way to remove the colouration inside the yaml comment? It's inconsistent with all other languages I've used in vim and makes readability unclear. As it stands it leaves huge blocks of colourised code which is commented and makes visually scanning a document hard.

Take this block for example, when commented out, it leaves almost as much highlighted as when not commented out

<img width="566" alt="image" src="https://github.com/user-attachments/assets/dc689c69-97cf-42c5-8200-9940dcddfeb2">

<img width="548" alt="image" src="https://github.com/user-attachments/assets/9e7ac9f2-9698-4ac2-b389-f6e453ef38cb">

**Comment by louisroyer** [comment]
You can remove the coloration by using jinja's comment syntax:
![2024-11-20T23:39:47,342363979+01:00](https://github.com/user-attachments/assets/5e7baba7-0a5d-439b-afbc-644af0927dd8)

**Comment by benswinburne** [comment]
I understand that I can use Jinja comments _within the template_ but what you've demonstrated above is no longer a valid yaml document. By commenting in the way you've described not only does it leave `trigger:` as an invalid empty property, but also the entire document can't be parsed now as Home Assistant only understands Jinja within particular properties of the yaml - in this case `value_template` - this is niche, granted, but valid nonetheless.

Whilst using Jinja comments inside the jinja is a valid use case, commenting out an entire block with # as a yaml comment is too.

Also, using commentary.vim for example, as you probably know widely used comment plugin for vim, it understands it should be commenting the yaml style not the jinja style and when using the comment keybinds, uses # not {#

**Comment by louisroyer** [comment]
This plugin is designed for files that are entirely j2 templates themselves and will expand to yaml once evaluated, not for yaml files that contains some properties being jinja templates (the opposite behavior).

For your use-case, you may modify the plugin like this:
```diff
diff --git a/syntax/yaml-jinja.vim b/syntax/yaml-jinja.vim
index f8c79e7..ce8361a 100644
--- a/syntax/yaml-jinja.vim
+++ b/syntax/yaml-jinja.vim
@@ -50,15 +50,15 @@ syn match jinjaAttribute contained /[a-zA-Z_][a-zA-Z0-9_]*/
 syn region jinjaNested matchgroup=jinjaOperator start="(" end=")" transparent display containedin=jinjaVarBlock,jinjaTagBlock,jinjaNested contained
 syn region jinjaNested matchgroup=jinjaOperator start="\[" end="\]" transparent display containedin=jinjaVarBlock,jinjaTagBlock,jinjaNested contained
 syn region jinjaNested matchgroup=jinjaOperator start="{" end="}" transparent display containedin=jinjaVarBlock,jinjaTagBlock,jinjaNested contained
-syn region jinjaTagBlock matchgroup=jinjaTagDelim start=/{%[-+]\?/ end=/[-+]\?%}/ containedin=ALLBUT,jinjaTagBlock,jinjaVarBlock,jinjaRaw,jinjaString,jinjaNested,jinjaComment
+syn region jinjaTagBlock matchgroup=jinjaTagDelim start=/{%[-+]\?/ end=/[-+]\?%}/ containedin=yamlBlockString
 
-syn region jinjaVarBlock matchgroup=jinjaVarDelim start=/{{-\?/ end=/-\?}}/ containedin=ALLBUT,jinjaTagBlock,jinjaVarBlock,jinjaRaw,jinjaString,jinjaNested,jinjaComment
+syn region jinjaVarBlock matchgroup=jinjaVarDelim start=/{{-\?/ end=/-\?}}/ containedin=yamlBlockString
 
 " Jinja template 'raw' tag
-syn region jinjaRaw matchgroup=jinjaRawDelim start="{%\s*raw\s*%}" end="{%\s*endraw\s*%}" containedin=ALLBUT,jinjaTagBlock,jinjaVarBlock,jinjaString,jinjaComment
+syn region jinjaRaw matchgroup=jinjaRawDelim start="{%\s*raw\s*%}" end="{%\s*endraw\s*%}" containedin=yamlBlockString
 
 " Jinja comments
-syn region jinjaComment matchgroup=jinjaCommentDelim start="{#" end="#}" containedin=ALLBUT,jinjaTagBlock,jinjaVarBlock,jinjaString,jinjaComment
+syn region jinjaComment matchgroup=jinjaCommentDelim start="{#" end="#}" containedin=yamlBlockString
 
 " Block start keywords.  A bit tricker.  We only highlight at the start of a
 " tag block and only if the name is not followed by a comma or equals sign
 ```
